# Generated by Django 5.1.1 on 2024-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка')),
                ('youtube_id', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='Id youtube')),
                ('thumbnail_url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка на миниатюру')),
                ('view_count', models.PositiveIntegerField(help_text='положительное число', verbose_name='число просмотров')),
            ],
            options={
                'verbose_name': 'клип',
                'verbose_name_plural': 'клипы',
            },
        ),
    ]
