# Generated by Django 5.1.1 on 2024-10-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0002_alter_clip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ('id',), 'verbose_name': 'клип', 'verbose_name_plural': 'клипы'},
        ),
    ]
