version: '3.8'

services:
  backend:
    build: .
    container_name: car_seller_backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: car_seller_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"

  redis:
     image: redis
     container_name: car_seller_redis
     command: redis-server /usr/local/etc/redis/redis.conf
     volumes:
       - .:/usr/local/etc/redis/redis.conf
     ports:
       - "6380:6379"

  celery:
     build: .
     container_name: car_seller_celery
     command: celery -A config worker -Q celery -l info
     depends_on:
       - postgres
       - redis