# Generated by Django 5.1.1 on 2024-09-26 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя автора')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия автора')),
                ('avatar_url', models.TextField(blank=True, help_text='ссылка в формате http/...', null=True, verbose_name='ссылка на аватарку')),
            ],
            options={
                'verbose_name': 'автор отзыва',
                'verbose_name_plural': 'авторы отзывов',
            },
        ),
        migrations.CreateModel(
            name='ReviewLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'площадка с отзывом',
                'verbose_name_plural': 'площадки с отзывом',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('stars', models.IntegerField(help_text='значение от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='звезд')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='review.reviewauthor', verbose_name='автор')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='review.reviewlocation', verbose_name='площадка на которой расположен')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
