# Generated by Django 5.1.1 on 2024-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewauthor',
            name='first_name',
            field=models.CharField(help_text='максимальная длина 100 символов', max_length=100, verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='reviewauthor',
            name='last_name',
            field=models.CharField(help_text='максимальная длина 100 символов', max_length=100, verbose_name='фамилия автора'),
        ),
    ]
