# Generated by Django 5.1.1 on 2024-09-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewauthor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewauthor',
            name='last_name',
            field=models.CharField(blank=True, help_text='максимальная длина 100 символов', max_length=100, null=True, verbose_name='фамилия автора'),
        ),
    ]
