# Generated by Django 5.1.1 on 2024-09-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_at',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
