# Generated by Django 5.1.1 on 2024-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewauthor',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название'),
        ),
    ]
