# Generated by Django 5.1.1 on 2024-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'контактная информация',
                'verbose_name_plural': 'контактная информация',
            },
        ),
        migrations.CreateModel(
            name='InformationAboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='контент')),
                ('block', models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='блок')),
            ],
            options={
                'verbose_name': 'информация об автосалоне',
                'verbose_name_plural': 'информация об автосалоне',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'социальная сеть',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='StagesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'этап работы',
                'verbose_name_plural': 'этапы работы',
            },
        ),
    ]
