# Generated by Django 5.1.1 on 2024-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0002_stagesofwork_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'настройка сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='stagesofwork',
            options={'ordering': ('position',), 'verbose_name': 'этап работы', 'verbose_name_plural': 'этапы работы'},
        ),
    ]
