# Generated by Django 5.1.1 on 2024-10-03 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0006_alter_questionnaire_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='phone_number',
            field=models.CharField(help_text="формат: '+79999999999'", max_length=16, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть определенного формата: '+7 999 999 99 99'.", regex='^\\+7 \\d{3} \\d{3} \\d{2} \\d{2}$')], verbose_name='номер телефона'),
        ),
    ]
