# Generated by Django 5.1.1 on 2024-10-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0008_alter_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=20, verbose_name='имя отправителя'),
        ),
    ]
