# Generated by Django 5.1.1 on 2024-10-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0011_alter_questionnaire_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
