# Generated by Django 5.1.1 on 2024-11-14 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0012_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='phone_number',
            field=models.CharField(help_text="формат: '+79999999999'", max_length=16, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть определенного формата: '+7XXXXXXXXXX'.", regex='^\\+7\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
