# Generated by Django 5.1.1 on 2024-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='id чата')),
            ],
            options={
                'verbose_name': 'телеграм чат',
                'verbose_name_plural': 'телеграм чаты',
            },
        ),
    ]
