# Generated by Django 5.1.1 on 2024-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0003_settings_alter_stagesofwork_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='content',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='name',
        ),
        migrations.AddField(
            model_name='settings',
            name='reviews_count',
            field=models.PositiveIntegerField(default=1, help_text='положительное число', verbose_name='количество отзывов для скачивания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='reviews_service_url',
            field=models.TextField(default=1, help_text='ссылка в формате http/...', verbose_name='ссылка на 2ГИС организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_channel_url',
            field=models.TextField(default=1, help_text='ссылка в формате http/...', verbose_name='ссылка на канал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_count_videos',
            field=models.PositiveIntegerField(default=1, help_text='положительное число', verbose_name='количество видео для скачивания'),
            preserve_default=False,
        ),
    ]
