# Generated by Django 5.1.1 on 2024-10-03 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0004_remove_settings_content_remove_settings_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть определенного формата: '+79999999999'.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
