# Generated by Django 5.1.1 on 2024-10-03 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0005_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='имя отправителя'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone_number',
            field=models.CharField(help_text="формат: '+79999999999'", max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть определенного формата: '+79999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='номер телефона'),
        ),
    ]
