# Generated by Django 5.1.1 on 2024-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_info', '0007_alter_questionnaire_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='имя отправителя'),
        ),
    ]
