# Generated by Django 5.1.1 on 2024-09-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='все форматы(кроме svg) конвертируются в webp', upload_to='images/%Y/%m/%d/', verbose_name='изображение')),
            ],
        ),
    ]
