# Generated by Django 5.1.1 on 2024-09-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
