# Generated by Django 5.1.1 on 2024-09-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_mileage_alter_car_price_and_more'),
        ('image', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ManyToManyField(related_name='car', to='image.image', verbose_name='изображение'),
        ),
    ]
