# Generated by Django 5.1.1 on 2024-10-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-price',), 'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
    ]
