# Generated by Django 5.1.1 on 2024-11-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0034_alter_carcolor_options_alter_carmark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_storage', models.PositiveIntegerField(help_text='в рублях', verbose_name='Склад, ЭПТС СБКТС, Услуга оформления')),
                ('commission_broker', models.PositiveIntegerField(help_text='в рублях', verbose_name='Перегон и сопутствующие регистрации')),
                ('commission', models.PositiveIntegerField(help_text='в рублях', verbose_name='комиссия')),
                ('commission_delivery', models.PositiveIntegerField(help_text='в валюте страны экспортера', verbose_name='комиссия в валюте экспортера')),
                ('japan_sanction_percent', models.PositiveIntegerField(blank=True, help_text='в процентах', null=True, verbose_name='Процент комиссии Японских санкционных авто')),
                ('japan_sanction_commission', models.PositiveIntegerField(blank=True, help_text='в валюте страны экспортера', null=True, verbose_name='комиссия в валюте экспортера для Японских санкционных авто')),
                ('korea_sanction_commission', models.PositiveIntegerField(blank=True, help_text='в валюте страны экспортера', null=True, verbose_name='комиссия в валюте экспортера для Корейских авто стоимостью выше 30 млн Вон')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'комиссия',
                'verbose_name_plural': 'комиссии',
                'ordering': ('country',),
            },
        ),
    ]
