# Generated by Django 5.1.1 on 2024-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewauthor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(verbose_name='дата добавления отзыва'),
        ),
    ]
