# Generated by Django 5.1.1 on 2024-09-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewauthor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reviewauthor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='reviewauthor',
            name='name',
            field=models.CharField(default=2, help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
    ]
