# Generated by Django 5.1.1 on 2024-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_reviewauthor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(verbose_name='дата добавления отзыва'),
        ),
    ]
