# Generated by Django 5.1.1 on 2024-09-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'марка автомобиля',
                'verbose_name_plural': 'марки автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'модель автомобиля',
                'verbose_name_plural': 'модели автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CountryManufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'страна производства',
                'verbose_name_plural': 'страны производства',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'тип двигателя',
                'verbose_name_plural': 'типы двигателя',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100, verbose_name='спецификация')),
                ('year_manufactured', models.PositiveIntegerField(verbose_name='год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='пробег')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car.carbrand', verbose_name='марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car.carmodel', verbose_name='модель')),
                ('country_manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car.countrymanufacturing', verbose_name='страна производства')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='car.enginetype', verbose_name='тип двигателя')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
            },
        ),
    ]
