# Generated by Django 5.1.1 on 2024-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(help_text='помощь', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(help_text='помощь', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='countrymanufacturing',
            name='name',
            field=models.CharField(help_text='помощь', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='name',
            field=models.CharField(help_text='помощь', max_length=255, unique=True, verbose_name='название'),
        ),
    ]
