# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carbrand_name_alter_carmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(help_text='положительное число', verbose_name='пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(help_text='положительное число', verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='specification',
            field=models.CharField(help_text='максимальная длина - 100 символов', max_length=100, verbose_name='спецификация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_manufactured',
            field=models.PositiveIntegerField(help_text='положительное число', verbose_name='год выпуска'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='countrymanufacturing',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
        ),
    ]
