# Generated by Django 5.1.1 on 2024-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='показывать в популярных'),
        ),
    ]
