# Generated by Django 5.1.1 on 2024-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarKPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'КПП автомобиля',
                'verbose_name_plural': 'КПП автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarPriv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Привод автомобиля',
                'verbose_name_plural': 'Привод автомобиля',
            },
        ),
    ]
