# Generated by Django 5.1.1 on 2024-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
                ('model_name', models.CharField(max_length=255, verbose_name='название поля фильтрации')),
            ],
            options={
                'verbose_name': 'базовый фильтр',
                'verbose_name_plural': 'базовые фильтры',
            },
        ),
    ]
