# Generated by Django 5.1.1 on 2024-10-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'марка автомобиля',
                'verbose_name_plural': 'марки автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='catalog.carmark', verbose_name='марка')),
            ],
            options={
                'verbose_name': 'модель автомобиля',
                'verbose_name_plural': 'модели автомобиля',
            },
        ),
    ]
