# Generated by Django 5.1.1 on 2024-10-06 04:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('table_name', models.CharField(help_text='максимальная длина - 20', max_length=20, verbose_name='название таблицы')),
            ],
            options={
                'verbose_name': 'страна производства',
                'verbose_name_plural': 'страны производства',
            },
        ),
        migrations.RemoveField(
            model_name='basefilter',
            name='content',
        ),
        migrations.RemoveField(
            model_name='basefilter',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='basefilter',
            name='name',
        ),
        migrations.AddField(
            model_name='basefilter',
            name='auction',
            field=models.CharField(default=1, help_text='исключаем аукционы содержащие эту часть в названии', max_length=20, verbose_name='название аукциона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='auction_date',
            field=models.PositiveIntegerField(default=1, help_text='за какой период от текущей даты (дней)', verbose_name='дата аукциона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='eng_v',
            field=models.PositiveIntegerField(default=1, help_text='строго больше какого значения', verbose_name='объем двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='finish',
            field=models.PositiveIntegerField(default=1, help_text='строго больше какого значения', verbose_name='финиш'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='kpp_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[1], help_text='исключаем эти типы', size=None, verbose_name='типы КПП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='marka_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['1'], help_text='исключаем эти марки', size=None, verbose_name='марки автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='mileage',
            field=models.PositiveIntegerField(default=1, help_text='меньше или равен какому значению', verbose_name='пробег'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='status',
            field=models.CharField(default=1, help_text='строго равен значению', max_length=50, verbose_name='статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='year',
            field=models.PositiveIntegerField(default=1, help_text='минимальный год для выборки', verbose_name='год выпуска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basefilter',
            name='country_manufacturing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='base_filter', to='catalog.country', verbose_name='страна производства'),
            preserve_default=False,
        ),
    ]
