# Generated by Django 5.1.1 on 2024-10-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_country_remove_basefilter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='country_manufacturing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='base_filter', to='catalog.country', verbose_name='страна производства'),
        ),
        migrations.AlterField(
            model_name='country',
            name='table_name',
            field=models.CharField(help_text='максимальная длина - 20', max_length=20, unique=True, verbose_name='название таблицы'),
        ),
    ]
