# Generated by Django 5.1.1 on 2024-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_basefilter_country_manufacturing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPriv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'привод автомобиля',
                'verbose_name_plural': 'приводы автомобиля',
            },
        ),
    ]
