# Generated by Django 5.1.1 on 2024-10-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_carcolor_name_remove_carpriv_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='country_manufacturing',
        ),
    ]
