# Generated by Django 5.1.1 on 2024-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_basefilter_country_manufacturing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='name',
            field=models.CharField(default=1, help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpriv',
            name='name',
            field=models.CharField(default=1, help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
    ]
