# Generated by Django 5.1.1 on 2024-10-07 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_carcolor_name_carpriv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpriv',
            name='api_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['1'], size=None, verbose_name='теги для Api'),
            preserve_default=False,
        ),
    ]
