# Generated by Django 5.1.1 on 2024-10-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_carpriv_api_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpriv',
            name='api_tags',
        ),
        migrations.CreateModel(
            name='CarPrivApiTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('priv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tag', to='catalog.carpriv', verbose_name='привод')),
            ],
            options={
                'verbose_name': 'api тэг привода автомобиля',
                'verbose_name_plural': 'api тэги привода автомобиля',
            },
        ),
    ]
