# Generated by Django 5.1.1 on 2024-10-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_carpriv_api_tags_carprivapitag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpriv',
            name='country_manufacturing',
        ),
        migrations.AddField(
            model_name='carprivapitag',
            name='country_manufacturing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='страна производства'),
            preserve_default=False,
        ),
    ]
