# Generated by Django 5.1.1 on 2024-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_carprivapitag_priv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='auction_date',
            field=models.PositiveIntegerField(blank=True, help_text='за какой период от текущей даты (дней)', null=True, verbose_name='дата аукциона'),
        ),
    ]
