# Generated by Django 5.1.1 on 2024-10-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_basefilter_auction_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPrivApiTag',
        ),
    ]
