# Generated by Django 5.1.1 on 2024-10-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_carprivapitag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPriv',
        ),
    ]
