# Generated by Django 5.1.1 on 2024-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_delete_carpriv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('course', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='курс')),
            ],
            options={
                'verbose_name': 'курс валют',
                'verbose_name_plural': 'курсы валют',
            },
        ),
    ]
