# Generated by Django 5.1.1 on 2024-10-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='course',
            field=models.DecimalField(decimal_places=4, help_text='стоимость одной единицы в рублях', max_digits=10, verbose_name='курс'),
        ),
    ]
