# Generated by Django 5.1.1 on 2024-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_currencyrate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='eng_v',
            field=models.DecimalField(decimal_places=1, help_text='строго больше какого значения (л)', max_digits=3, verbose_name='объем двигателя'),
        ),
    ]
