# Generated by Django 5.1.1 on 2024-10-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_basefilter_eng_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcolor',
            name='country_manufacturing',
        ),
        migrations.CreateModel(
            name='CarColorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.carcolor', verbose_name='цвет')),
                ('country_manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='страна производства')),
            ],
            options={
                'verbose_name': 'тег цвета автомобиля',
                'verbose_name_plural': 'теги цвета автомобиля',
            },
        ),
    ]
