# Generated by Django 5.1.1 on 2024-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_remove_carcolor_country_manufacturing_carcolortag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcolortag',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название'),
        ),
    ]
