# Generated by Django 5.1.1 on 2024-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_carcolortag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmark',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название'),
        ),
        migrations.AlterUniqueTogether(
            name='carmark',
            unique_together={('name', 'country_manufacturing')},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('name', 'mark')},
        ),
    ]
