# Generated by Django 5.1.1 on 2024-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_carcolortag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='status',
            field=models.CharField(blank=True, help_text='строго равен значению', max_length=50, null=True, verbose_name='статус'),
        ),
    ]
