# Generated by Django 5.1.1 on 2024-10-10 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_basefilter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilter',
            name='priv',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='исключаем эти приводы', null=True, size=None, verbose_name='привод автомобиля'),
        ),
        migrations.AlterField(
            model_name='basefilter',
            name='marka_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='исключаем эти марки', null=True, size=None, verbose_name='марки автомобиля'),
        ),
    ]
