# Generated by Django 5.1.1 on 2024-10-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_basefilter_priv_alter_basefilter_marka_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='country_manufacturing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='страна производства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='name',
            field=models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название'),
        ),
        migrations.AlterUniqueTogether(
            name='carcolor',
            unique_together={('name', 'country_manufacturing')},
        ),
    ]
