# Generated by Django 5.1.1 on 2024-10-13 04:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_carcolor_country_manufacturing_alter_carcolor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='kpp_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), help_text='исключаем эти типы, несколько значений разделяются запятой', size=None, verbose_name='типы КПП'),
        ),
        migrations.AlterField(
            model_name='basefilter',
            name='marka_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='исключаем эти марки, несколько значений разделяются запятой', null=True, size=None, verbose_name='марки автомобиля'),
        ),
        migrations.AlterField(
            model_name='basefilter',
            name='priv',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='исключаем эти приводы, несколько значений разделяются запятой', null=True, size=None, verbose_name='привод автомобиля'),
        ),
    ]
