# Generated by Django 5.1.1 on 2024-10-15 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_basefilter_kpp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilter',
            name='rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='берем только эти оценки, несколько значений разделяются запятой', null=True, size=None, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='basefilter',
            name='kpp_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), help_text='берем только эти типы, несколько значений разделяются запятой', size=None, verbose_name='типы КПП'),
        ),
    ]
