# Generated by Django 5.1.1 on 2024-10-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_basefilter_rate_alter_basefilter_kpp_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcolor',
            options={'ordering': ('name',), 'verbose_name': 'цвет автомобиля', 'verbose_name_plural': 'цвета автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carmark',
            options={'ordering': ('name',), 'verbose_name': 'марка автомобиля', 'verbose_name_plural': 'марки автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('name',), 'verbose_name': 'модель автомобиля', 'verbose_name_plural': 'модели автомобиля'},
        ),
    ]
