# Generated by Django 5.1.1 on 2024-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_basefilter_max_eng_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_icon',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='символ валюты'),
        ),
    ]
