# Generated by Django 5.1.1 on 2024-10-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_carmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'цвет автомобиля',
                'verbose_name_plural': 'цвета автомобиля',
            },
        ),
    ]
